[project]
name = "1-setup-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "dbt-core>=1.9.8",
    "dbt-postgres>=1.9.0",
    "duckdb>=1.3.0",
    "faker>=37.4.0",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
]
